In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv('amazon.csv')
df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

1. Check the data types of all columns. Which ones should be numeric but are currently stored as strings?

In [2]:
df.dtypes
#discounted_price,actual_price,discount_percentage and rating shold be in float and rating_count should be in integer

product_id             object
product_name           object
category               object
discounted_price       object
actual_price           object
discount_percentage    object
rating                 object
rating_count           object
about_product          object
user_id                object
user_name              object
review_id              object
review_title           object
review_content         object
img_link               object
product_link           object
dtype: object

2. cleaning discounted_price and actual_price (stripping the ₹ symbol and commas, then converting to float)

In [3]:
df['discounted_price']= df['discounted_price'].str.replace('₹','').str.replace(',','')
df['actual_price']= df['actual_price'].str.replace(',','').str.replace('₹','')
df[['discounted_price','actual_price']] = df[['discounted_price','actual_price']].astype(float)

In [4]:
df[['discounted_price','actual_price']].dtypes

discounted_price    float64
actual_price        float64
dtype: object

3. Clean discount_percentage: remove the % sign and convert to float.

In [5]:
df['discount_percentage']= df['discount_percentage'].str.replace('%','')
df['discount_percentage'] = df['discount_percentage'].astype(float)

In [6]:
df['discount_percentage'].dtypes

dtype('float64')

4. Clean rating_count: remove commas and convert to numeric. What happens to the 2 missing values — check what's actually in those rows before deciding whether to drop or fill them.

In [7]:
df[df['rating_count'].isnull()]
df = df.dropna(subset=['rating_count'])

In [8]:
df['rating_count']= df['rating_count'].str.replace(',','')
df['rating_count'] = df['rating_count'].astype(int)

In [9]:
df['rating_count'].dtypes

dtype('int64')

5. Try converting rating to numeric using pd.to_numeric(). You'll likely hit an error — find out which row(s) are causing it and decide how to handle it.

In [10]:
df['rating'] = pd.to_numeric(df['rating'])

ValueError: Unable to parse string "|" at position 1277

In [11]:
df[df['rating'] == '|']

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
1279,B08L12N5H1,Eureka Forbes car Vac 100 Watts Powerful Sucti...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...",2099.0,2499.0,16.0,|,992,No Installation is provided for this product|1...,"AGTDSNT2FKVYEPDPXAA673AIS44A,AER2XFSWNN4LAUCJ5...","Divya,Dr Nefario,Deekshith,Preeti,Prasanth R,P...","R2KKTKM4M9RDVJ,R1O692MZOBTE79,R2WRSEWL56SOS4,R...","Decent product,doesn't pick up sand,Ok ok,Must...","Does the job well,doesn't work on sand. though...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Eureka-Forbes-Vacuum-Cle...

In [12]:
df['rating'] = pd.to_numeric(df['rating'],errors= 'coerce')
df[df['rating'].isnull()]
df = df.dropna(subset='rating')

In [13]:
df[df['rating'].isnull()]

Empty DataFrame
Columns: [product_id, product_name, category, discounted_price, actual_price, discount_percentage, rating, rating_count, about_product, user_id, user_name, review_id, review_title, review_content, img_link, product_link]
Index: []

6. Split the category column on | and extract just the top-level category (e.g. "Computers&Accessories") into a new column.

In [16]:
df['main_category'] = df['category'].str.split('|').str[0]
df.head(1)

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link,main_category
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,399.0,1099.0,64.0,4.2,24269,High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...,Computers&Accessories

7. Find how many unique top-level categories exist, and the count of products in each.

In [32]:
df['main_category'].value_counts()

main_category
Electronics              526
Computers&Accessories    451
Home&Kitchen             447
OfficeProducts            31
MusicalInstruments         2
HomeImprovement            2
Toys&Games                 1
Car&Motorbike              1
Health&PersonalCare        1
Name: count, dtype: int64

In [31]:
df['main_category'].nunique()

9

8. Find the top 10 most common full category paths (before splitting) — i.e. use the original category column, not main_category.

In [41]:
top_level_catg = df['category'].value_counts().head(10)
top_level_catg

category
Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables                        231
Electronics|WearableTechnology|SmartWatches                                                               76
Electronics|Mobiles&Accessories|Smartphones&BasicMobiles|Smartphones                                      68
Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions                                             63
Electronics|Headphones,Earbuds&Accessories|Headphones|In-Ear                                              52
Electronics|HomeTheater,TV&Video|Accessories|RemoteControls                                               49
Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|MixerGrinders                                  27
Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables                                            24
Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|Irons|DryIrons     24
Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Mice                            24
Name: count, dtype: int64

9. Calculate the actual savings (actual_price - discounted_price) for each product as a new column.

In [38]:
df['actual_saving'] = df['actual_price'] - df['discounted_price']

In [39]:
df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link,main_category,actual_saving
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,399.0,1099.0,64.0,4.2,24269,High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...,Computers&Accessories,700.0
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,199.0,349.0,43.0,4.0,43994,"Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...,Computers&Accessories,150.0
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,199.0,1899.0,90.0,3.9,7928,【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...,Computers&Accessories,1700.0
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,329.0,699.0,53.0,4.2,94363,The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...,Computers&Accessories,370.0
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,154.0,399.0,61.0,4.2,16905,[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...,Computers&Accessories,245.0

10. Find the average discount percentage per top-level category.

In [49]:
df.groupby('main_category')['discount_percentage'].mean().sort_values(ascending=False).round(2).head(3)

main_category
HomeImprovement          57.50
Computers&Accessories    53.92
Health&PersonalCare      53.00
Name: discount_percentage, dtype: float64

11. Find the 10 products with the highest discount percentage.

In [57]:
df.sort_values('discounted_price',ascending=False).head(10)[['product_name','discounted_price']]

                                           product_name  discounted_price
249   Sony Bravia 164 cm (65 inches) 4K Ultra HD Sma...           77990.0
325   OnePlus 163.8 cm (65 inches) U Series 4K LED S...           61999.0
255   VU 164 cm (65 inches) The GloLED Series 4K Sma...           54990.0
192   Samsung 138 cm (55 inches) Crystal 4K Neo Seri...           47990.0
283   LG 139 cm (55 inches) 4K Ultra HD Smart LED TV...           47990.0
332   MI 138.8 cm (55 inches) 5X Series 4K Ultra HD ...           46999.0
276   Samsung 138 cm (55 inches) Crystal 4K Series U...           45999.0
533   OnePlus 10T 5G (Moonstone Black, 8GB RAM, 128G...           44999.0
216   OnePlus 138.7 cm (55 inches) U Series 4K LED S...           42999.0
1354  LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...           42990.0

12. Find the 10 highest-rated products that also have more than 1000 rating_count (to avoid products with just 1–2 ratings skewing results).

In [63]:
rating_1000= df[df['rating_count']>1000].sort_values(by='rating',ascending=False).head(10)
rating_1000

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link,main_category,actual_saving
1299,B0B53DS4TF,"Instant Pot Air Fryer, Vortex 2QT, Touch Contr...",Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,4995.0,20049.0,75.0,4.8,3964,VOLTAGE (230 Volts): Instant Vortex Air Fryer ...,"AGXJAYXZKJ6NCPSLX57MXJLQ3F6Q,AEQYSJWBP6DN2IV2L...","nikhil,Rituja Ray,Prasan Krishnan Karthikeyan,...","R2FHIBV8JE4CTB,R315K0BCU0KVKO,RD129PA7KQQOR,R3...","Loved it,Good product,Good product,It's easy t...",I have used multiple air fryers. But this one ...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Instant-Vortex-2QT-EvenC...,Home&Kitchen,15054.0
1145,B0BR4F878Q,Swiffer Instant Electric Water Heater Faucet T...,"Home&Kitchen|Heating,Cooling&AirQuality|WaterH...",1439.0,1999.0,28.0,4.8,53803,✔Quick Electric Hot Water Tap Heating tube: hi...,"AEU7DVFEL43XZ6T4D572W2ZLBRKQ,AGWOH7CFDMUVW52NM...","Yogita g.,Amazon Customer,Mimsy","R2WHW4PEF14WOD,R2DCCZWUGI0O0K,R1FA1HH6VL1RAL","Best Product,It’s expansive but it works well ...",Must buy best Fabulous product I recommend thi...,https://m.media-amazon.com/images/I/41+t2HWvwF...,https://www.amazon.in/Swiffer-Instant-Electric...,Home&Kitchen,560.0
1388,B0BP89YBC1,Campfire Spring Chef Prolix Instant Portable W...,"Home&Kitchen|Heating,Cooling&AirQuality|WaterH...",1499.0,3500.0,57.0,4.7,2591,Prolix Auto cut off feature: It is available w...,"AEVX4JV3C4QR3Y3V3RJXQ2WZAR4Q,AHR5JZBK66QYZSEJ3...","Srujan kumar,Sadhu s.,parveen sharma,Patel kau...","RBPM3YRVWMMMK,RVY7BZCJPHJZU,R3KXHKIGWPT7IS,R1K...","Felt very useful 👌 but cable is short,Good in ...","I like instant heating, I didn't get warranty ...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Spring-Chef-Stainless-Re...,Home&Kitchen,2001.0
249,B09WN3SRC7,Sony Bravia 164 cm (65 inches) 4K Ultra HD Sma...,"Electronics|HomeTheater,TV&Video|Televisions|S...",77990.0,139900.0,44.0,4.7,5935,Resolution: 4K Ultra HD (3840 x 2160) | Refres...,"AF6Z2OYIXRPZJHVYN2MFKKYHPHFQ,AH5SAORYVUN5MGIBL...","David P.,Dr. ATUL THAKUR,Shriniwas Patil,Tahir...","R16HCZ0W1TRSMM,R12J7UKQ0FX3O9,R8729SR7LQFUU,R1...",Product installation was excellent but delive...,The delivery people were not careful with the ...,https://m.media-amazon.com/images/I/51uVckL1jR...,https://www.amazon.in/Sony-Bravia-inches-Googl...,Electronics,61910.0
1223,B0BM4KTNL1,"FIGMENT Handheld Milk Frother Rechargeable, 3-...",Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,699.0,1599.0,56.0,4.7,1729,【Rechargeable Multi-Function Milk Frother】The ...,"AGMHHTX7GPWHZAUTEYQOFEEDFMDQ,AEJJGJQCIEPL3ZBNU...","123MovieTime,Ravneet S.,Akash,Mohd Amaan,Panka...","R1YXOQ6ZZI33LZ,R17FVMZGPYPOYZ,R23NCERA0R891T,R...","Nice product,Not as effective as claimed, just...","Value for money,Not as effective as claimed, j...",https://m.media-amazon.com/images/I/51oN+8Zs5Y...,https://www.amazon.in/FIGMENT-Rechargeable-Dec...,Home&Kitchen,900.0
1275,B0BM9H2NY9,Multifunctional 2 in 1 Electric Egg Boiling St...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,699.0,1599.0,56.0,4.7,2300,Egg Frying Pan,"AFZ2YKWX4KR7MWSA6UOMEGGHT32A,AEP6WZ7AR6XDQSBFS...","Nitin G.,Veerasomachary,Roshan,Kunwar Indransh...","R2DHTJGY77MOP0,R36IXNHZC037AW,R3GPHUMRV75VWK,R...","Amazing! Value for money!,Very easy to use,2 i...","Worth buying for eggetarians,Working great so ...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Multifunctional-Electric...,Home&Kitchen,900.0
459,B0B23LW7NV,Spigen EZ Fit Tempered Glass Screen Protector ...,Electronics|Mobiles&Accessories|MobileAccessor...,999.0,2899.0,66.0,4.7,7779,Compatibility ; Glass Screen Protector Compati...,"AGQIXFPHABUZ2WPETGRYDB7VSMXA,AECPF7WFMUQ3TR7YT...","VK,Siddhi Prabhudesai,Prashant Nair,Srihare,Ni...","R13CIOIUD1D8UM,R17AIJTSM1FUNS,R3AJ1T3JVA8O9V,R...","Easy to install,Best screen guard and the easi...",It is easy to install at home. The kit has all...,https://m.media-amazon.com/images/I/51EiPNlJDg...,https://www.amazon.in/Spigen-Tempered-Screen-P...,Electronics,1900.0
1428,B078JT7LTD,"Sujata Dynamix, Mixer Grinder, 900 Watts, 3 Ja...",Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,6120.0,8073.0,24.0,4.6,2751,Warranty: 2 year warranty provided by the manu...,"AGS4ODHNPY3TQGAIJFDY4I33URHA,AFFSSRKP2H3OGXCIJ...","Tengop,Jeevan Gaikwad,gunashekar,Vibha K.,Amaz...","R1LBKT3YDVVW86,R2PNLSWFYW5QEF,R2I6NKZE7JWNY6,R...","Good product,Quality is great but chuteney jar...",Got it with intact packaging open it up the mo...,https://m.media-amazon.com/images/I/415634DtKf...,https://www.amazon.in/Sujata-Dynamix-900W-900-...,Home&Kitchen,1953.0
137,B08TGG316Z,"10k 8k 4k HDMI Cable, Certified 48Gbps 1ms Ult...","Electronics|HomeTheater,TV&Video|Accessories|C...",999.0,2399.0,58.0,4.6,3664,Certified HDMI Cable: The package has an offic...,"AFO7T5DJCA34LXNLPEMNTUPHBA3Q,AEOKQXQO42VI27RS7...","Mandar Joglekar,Vasanth,Well person","R1482M3Z6TF62M,RX9ISCNT5KUMA,RY1MX82BJD2VD","Fantastic Ultra High Speed HDMI cable,Amazing ...",Absolutely value for money. I connect it with ...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Cable-Certified-48Gbps-U...,Electronics,1400.0
886,B01MQ2A86A,"Logitech M331 Silent Plus Wireless Mouse, 2.4G...",Computers&Accessories|Accessories&Peripherals|...,1295.0,1645.0,21.0,4.6,12375,Quieter Click: Logitech’s SilentTouch Technolo...,"AE6TTPY5R4YW3XHTPGX6CGHLMVGA,AG5CBSM4UJ7KPPFIQ...","Awesome Shopper,Suresh madaka,Amazon Customer,...","R17S7JVWFH1X6W,R1HINIS5AG6PXD,R3VZFLZVFVZ13G,R...","Good but the scroll is now damaged,Nice,Noisel...",- excellent piece of wireless mouse- reasonabl...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Logitech-Silent-Wireless...,Computers&Accessories,350.0

13. group by top-level category and find average rating — which category has the most satisfied customers on average?

In [67]:
df.groupby('main_category')['rating'].mean().sort_values(ascending=False).round(2)
#OfficeProducts has the most satisfied customers on average

main_category
OfficeProducts           4.31
Toys&Games               4.30
HomeImprovement          4.25
Computers&Accessories    4.16
Electronics              4.08
Home&Kitchen             4.04
Health&PersonalCare      4.00
MusicalInstruments       3.90
Car&Motorbike            3.80
Name: rating, dtype: float64

14. Find how many products have "Fast" or "fast" in their product_name.

In [77]:
df['product_name'].str.contains('Fast', case= False).sum()

np.int64(206)

15. Count how many unique user_id values exist — but note this column sometimes contains multiple comma-separated user IDs per row (multiple reviewers). Split and count actual unique reviewers.

In [94]:
actual_unique_reviewers = df['user_id'].str.split(',').explode().str.strip()
actual_unique_reviewers.nunique()

9040

16. Find the average length (word count) of review_content — does a longer review correlate with a higher or lower rating?

In [99]:
df.head()
df['review_word_count']= df['review_content'].str.split().str.len()
df['review_word_count'].mean().round(2)
df['review_word_count'].describe()

count    1462.000000
mean      240.920657
std       316.813372
min        13.000000
25%        81.000000
50%       139.500000
75%       243.000000
max      2974.000000
Name: review_word_count, dtype: float64

In [100]:
corelation = df['review_word_count'].corr(df['rating'])
corelation

np.float64(0.0796432187149448)

17. Verify your cleaned discount_percentage roughly matches 1 - (discounted_price / actual_price) — do the numbers align, or is there a mismatch worth investigating?

In [102]:
df['implied_discount'] = (1 - df['discounted_price'] / df['actual_price']) * 100

In [103]:
df['discount_diff'] = df['discount_percentage'] - df['implied_discount']

In [104]:
df['discount_diff'].describe()

count    1462.000000
mean        0.006667
std         0.264217
min        -0.498382
25%        -0.164854
50%        -0.013753
75%         0.219135
max         0.500000
Name: discount_diff, dtype: float64

18. After all cleaning, print df.dtypes again to confirm every column that should be numeric now actually is.

In [105]:
df.dtypes

product_id              object
product_name            object
category                object
discounted_price       float64
actual_price           float64
discount_percentage    float64
rating                 float64
rating_count             int64
about_product           object
user_id                 object
user_name               object
review_id               object
review_title            object
review_content          object
img_link                object
product_link            object
main_category           object
actual_saving          float64
act_userid              object
review_word_count        int64
implied_discount       float64
discount_diff          float64
dtype: object